### ISSUE TITLE
race condition in detail views

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#60]
1) Clicking on attendeeList button before minimap finish loading will cause NPE

07-16 01:35:07.545    2122-2122/com.sms.partyview E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3509)
            at android.view.ViewGroup.addView(ViewGroup.java:3380)
            at android.view.ViewGroup.addView(ViewGroup.java:3356)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.sms.partyview.fragments.EventMapFragment.onCreateView(EventMapFragment.java:176)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:446)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mydiemho** [comment]
2)  a similar race condition when you press accept/reject in invite detail

**Comment by simonque** [comment]
Fixed (2) : https://github.com/eecsninja/partyview/commit/f6e6532e018bc3ed0464fe496a34324fadf166e2

**Comment by simonque** [comment]
(1) no longer applies due to changes in structure
