### ISSUE TITLE
Getting NPE on event creation

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#67]
Not sure how to reproduce. We can just inspect the code.

Caused by: java.lang.NullPointerException
            at com.sms.partyview.fragments.EventTabsFragment.respondToEventCreation(EventTabsFragment.java:65)
            at com.sms.partyview.activities.HomeActivity.onActivityResult(HomeActivity.java:191)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)

**Comment by mydiemho** [comment]
this might not happen anymore with this change: https://github.com/eecsninja/partyview/commit/b36fa9343ca4d0f0ea6a70f3605e63f0754774c6
